### ISSUE TITLE
`\[` and `&` inside braces parse error

### ISSUE THREAD

**Issue by imarabinda** [remarkjs/remark-math#100]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

remark-math@6.0.0

### Steps to reproduce

Try to render this content
`\[ \text{SG&A as a percentage of revenue} = \left( \frac{\text{SG&A expenses}}{\text{Revenue}} \right) \times 100\% \]`

### Expected behavior

It should render math notation like this.
![Screenshot from 2024-10-25 14-57-01](https://github.com/user-attachments/assets/a319c85e-6b12-46f7-8628-35bbc44bdad1)

### Actual behavior

Getting this error 
`ParseError: KaTeX parse error: Expected 'EOF', got '&' at position 9: \text{SG&̲A Percentage} `

### Affected runtime and version

node@20.17.0

### Affected package manager and version

npm@10.8.3

### Affected OS and version

Ubuntu 22.04.5 LTS

### Build and bundle tools

Next.js

**Comment by wooorm** [comment]
Please see the readme; that is not the syntax this project uses.
