### ISSUE TITLE
[Bug] Cannot parse `\$` and line break `$$` syntax

### ISSUE THREAD

**Issue by zhuozhiyongde** [remarkjs/remark-math#101]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

"rehype-katex": "^7.0.0"; "remark-math": "^6.0.0"

### Steps to reproduce

```latex
$ \$ $
```

```latex
$$ \begin{aligned}
\log p(x) &= \log \int p(x|z)p(z)dz \\
&= \log \int \frac{q(z|x)}{q(z|x)}p(x|z)p(z)dz \\
&\geq \int q(z|x)\log\frac{p(x|z)p(z)}{q(z|x)}dz \\
&= \mathbb{E}_{q(z|x)}[\log p(x|z)] - D_{KL}(q(z|x)||p(z)) \\
&= \text{ELBO}
\end{aligned} $$
```

### Expected behavior

![image](https://github.com/user-attachments/assets/1a949853-72fc-4a8b-9a39-f7011d0e1f3e)

### Actual behavior

![LobeChat 2024-10-27 12 07 07](https://github.com/user-attachments/assets/14179b52-bcdd-41db-ab06-10f3882aeac8)

### Affected runtime and version

node@18.17.1

### Affected package manager and version

pnpm@9.12.0

### Affected OS and version

macOS Sonoma

### Build and bundle tools

Vite, Next.js

**Comment by ntaylor-ads** [comment]
The continue extension for VScode uses remarkMath and is experiencing this issue. Equations of the format: 
$$
\sin\theta \approx \theta, \quad \cos\theta \approx 1,
$$
cause the entire document to not render. [Here is the issue](https://github.com/continuedev/continue/issues/3068)
