### ISSUE TITLE
Not working with svelte

### ISSUE THREAD

**Issue by tobiasBora** [remarkjs/remark-math#104]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=issues) and [discussions](https://github.com/orgs/remarkjs/discussions) and couldn’t find anything (or linked relevant results below)

### Affected package

rehype-katex@7.0.1

### Steps to reproduce

Rehype-katex does not work with svelte with simple expressions involving `\mathbb{N}` or `\sqrt{x}`, apparently due to the fact that svelte interprets `{}` as a template. Other projects like https://github.com/kwshi/rehype-katex-svelte have been created to solve this issue using instead `{@html "..."}`, but they seem unmaintained.

To reproduce:

Clone https://github.com/tobiasBora/understand-pid-algo/commit/af0b30e9ffcfc7b55b19cb5a023b28b3acc20aac and checkout to the commit af0b30e9ffcfc7b55b19cb5a023b28b3acc20aac, run `npm run dev`, and visit the home page. 

### Actual behavior

Observe that you have an error due to the line:
```
$$x + \frac{1}{\sqrt{2 + \delta}} \in \mathbb{N}$$
```
the error being on the sqrt:
```
src/routes/+page.svx:80:15 Expecting Unicode escape sequence \uXXXX
https://svelte.dev/e/js_parse_error

src/routes/+page.svx:80:15

78 |  <p><span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>x</mi><mo>+</mo><mfrac><mn>1</mn><msqrt><mrow><mn>2</mn><mo>+</mo><mi>δ</mi></mrow></msqrt></mfrac><mo>∈</mo><mi mathvariant="double-struck">N</mi></mrow><annotation
 79 |    encoding="application/x-tex"
 80 |  >x + \frac{1}{\sqrt{2 + \delta}} \in \mathbb{N}</annotation></semantics></math></span><span
                      ^
 81 |    class="katex-html"
 82 |    aria-hidden="true"
```

### Expected behavior

Should work as his expression is valid latex.

### Runtime

node@20.18.1

### Package manager

npm@10.8.2

### Operating system

NixOs unstable

### Build and bundle tools

Vite

**Comment by ChristianMurphy** [comment]
Welcome @tobiasBora! 👋 
That is expected, Rehype handles HTML, Svelte templates are not HTML.
There is no plan or intent to make a svelte mode for the HTML generate in rehype.

That said, there is still a way to handle this.
Instead of trying to treat HTML as Svelte, have rehype render to svelte through it's programatic API.
In particular have rehype render JSX constructs (https://github.com/rehypejs/rehype-react) then having Svelte use that programmatic API to safely render to a Svelte component (https://github.com/kenoxa/svelte-jsx).

**Comment by tobiasBora** [comment]
@ChristianMurphy Thanks, even if I'm a bit sad to see that there is no plan to solve this. But I'm curious, would it make sense to allow the user to define a custom wrapper code around the html produced by remark-math? This may be a wrapper like `<div class="remark-math">…</div>` or, for svelte, `{@html "..."}`… As such, I guess this is still valid HTML (if you interpret this as a single of tokens I don't see why this would be invalid html), and this would certainly be really easy to implement.

>  Svelte templates are not HTML.

Out of curiosity, aren't they valid HTML syntaxically? Like in HTML, nothing prevents me from writing `Foo {x+1} bar`, irrespective of the semantic given by svelte to `{x+1}`.

> That said, there is still a way to handle this. Instead of trying to treat HTML as Svelte, have rehype render to svelte through its programatic API.

Hum interesting, I need to check how far I can go with this. But I guess I will not be able anymore to use svelte-syntax in the html like:
```
---
title: my title
---
<script>
let x = 1;
</script>

## Introduction

Hey {x + 2}.
```

**Comment by wooorm** [comment]
It would make a lot of sense yes to wrap things. It already exists: that wrapper is `mdsvex`. That is where Svelte comes in. It turns AST nodes into a string for Svelte to consume.

Note: `mdsvex` is different from MDX.

MDX itself also supports Svelte, somewhat. It should not have these problems: https://mdxjs.com/docs/getting-started/#jsx.

That being said, Svelte does not itself implement a JSX runtime, which is why `svelte-jsx` exists. And it might not be perfect yet. You can either improve it, or ask Rich to implement the JSX automatic runtime: https://github.com/sveltejs/svelte/issues/8256#issuecomment-1422962230.

**Comment by tobiasBora** [comment]
> It would make a lot of sense yes to wrap things. It already exists: that wrapper is mdsvex. That is where Svelte comes in. It turns AST nodes into a string for Svelte to consume.

So if my understanding is correct, for now stuff goes like `markdown file > rehype-katex > mdsvex > svelte`, so when mdsvex sees the AST, it already lost the information that some parts should not be parsed by svelte (unless they look for hardcoded class and exclude some classes from being parsed by svelte if this makes sense?). So it means that this should rather be done by rehype-katex running something like what is done by rehybe-katex-svelte:
```
      hastFromString(node, `{@html ${JSON.stringify(rendered)}}`);
```

Regarding MDX it is another option to try if you say it should work, but I guess I lose some of the nice integration between mdsvex and svelte (like I can call a svelte component from the markdown)… And also svelte-jsx seems unmaintained and https://github.com/sveltejs/svelte/issues/8256 mentions it is also buggy, so this seems overkill compared to a ~ one-line addition to rehype-katex…

In the worst case, if neither you nor mdsvex want to implement a solution, would it make sense to create a rehype plugin running right after rehype-katex that picks all div with class like `math`, `math-inline` or `math-display` and surround them with a `{@html "…"}` code?
