### ISSUE TITLE
rehype-katex: can't hanlde `\end{cases}$$`

### ISSUE THREAD

**Issue by steve02081504** [remarkjs/remark-math#105]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=issues) and [discussions](https://github.com/orgs/remarkjs/discussions) and couldn’t find anything (or linked relevant results below)

### Affected package

rehype-katex

### Steps to reproduce

code: https://github.com/steve02081504/fount/blob/0183423e52859c93fa26b910028f43a9e8380365/src/public/scripts/markdown.mjs#L32
not work:
````markdown
$$\begin{cases}
h(0) = 0 \\
h'(0) = 1
\end{cases}$$
````
works:
````markdown
$$
\begin{cases}
h(0) = 0 \\
h'(0) = 1
\end{cases}
$$
````

### Actual behavior

not work: `ParseError: KaTeX parse error: Expected 'EOF', got '\end' at position 23: …0 \\
h'(0) = 1
\̲e̲n̲d̲{cases}$$`

### Expected behavior

should work

### Runtime

firefox dev

**Comment by ChristianMurphy** [comment]
Math blocks work like code blocks.
They are expected to be on newline by themselves.

There is a more technical explanation in the syntax guide.
https://github.com/micromark/micromark-extension-math#syntax
