### ISSUE TITLE
rehype-katex not rendering square roots

### ISSUE THREAD

**Issue by mglsj** [remarkjs/remark-math#106]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=issues) and [discussions](https://github.com/orgs/remarkjs/discussions) and couldn’t find anything (or linked relevant results below)

### Affected package

rehype-katex@7.0.1

### Steps to reproduce

Use sqrt function in latex.

vs code
![image](https://github.com/user-attachments/assets/711fbe50-e2ae-4b08-81de-827c5736d365)

### Actual behavior

website
![image](https://github.com/user-attachments/assets/3f8e663a-11af-461f-ad13-a4f7b2157243)

### Expected behavior

$$
= \sqrt{104.22} = 10.21
$$

### Runtime

node@latest

### Package manager

pnpm@latest

### Operating system

Windows 11

### Build and bundle tools

Astro

**Comment by ChristianMurphy** [comment]
@mglsj two likely reasons to check
1. Latex needs css to render correctly, make sure you imported it
2. Escapes in markdown and JS work differently due to JS strings also using escapes for controls. If you are defining Latex in JS make sure to type the backslash twice

**Comment by mglsj** [comment]
> @mglsj two likely reasons to check
> 
> 1. Latex needs css to render correctly, make sure you imported it
> 
> 2. Escapes in markdown and JS work differently due to JS strings also using escapes for controls. If you are defining Latex in JS make sure to type the backslash twice

This problem is only with the sqrt function. Every other symbol (fraction, integral, powers) works

**Comment by ChristianMurphy** [comment]
@mglsj pleases share a reproducible example.
Using https://stackblitz.com/github/remarkjs/.github/tree/main/sandbox-templates/remark-rehype-with-vite?file=package.json as a starter.

**Comment by mglsj** [comment]
> @mglsj pleases share a reproducible example. Using https://stackblitz.com/github/remarkjs/.github/tree/main/sandbox-templates/remark-rehype-with-vite?file=package.json as a starter.

https://stackblitz.com/edit/github-5igvexku?file=src%2Fcontent%2Fdocs%2Findex.mdx

**Comment by ChristianMurphy** [comment]
That is an Astro issue, with remark math and rehype katex it works fine
reproducible example: https://stackblitz.com/edit/github-ncxm4j1s?file=src%2Fmain.ts

We've seen similar issues before, most likely the issue is with the escaping done by Astro.
