### ISSUE TITLE
Use KaTeX AST instead of reparsing the whole tree

### ISSUE THREAD

**Issue by sandhose** [remarkjs/remark-math#16]
Right now remark-math uses KaTeX's `renderToString` method to generate HTML, then reparses it directly afterwards using `rehype-parse`.

This is expensive, but was necessary because KaTeX used to not expose their internal AST.

I opened a while ago an issue on their side to expose this AST in order to have better renderers. It seems like now they do. https://github.com/Khan/KaTeX/issues/800#issuecomment-347196364

It would be great if `remark-math` did the conversion from KaTeX's AST to HAST nodes directly, instead of parsing the stringified DOM tree

**Comment by Rokt33r** [comment]
Sounds reasonable!

**Comment by ibrahima** [comment]
Just to be clear, this is only applicable to `remark-html-katex`, right? `remark-html` itself has nothing to do with KaTeX, it's just parsing out LaTeX nodes for remark?

**Comment by wooorm** [comment]
@ibrahima This relates to `rehype-katex` and `remark-html-katex`. They both include an HTML parser because KaTeX spits out an HTML string that needs to be transformed into our AST.

I’ve reacher out to KaTeX people again and may be able to work on using hast in KaTeX.

**Comment by wooorm** [comment]
I don’t think it’s useful to track this there as it’s tracked upstream. Closing.
