### ISSUE TITLE
adding LaTeX environment without mathmode

### ISSUE THREAD

**Issue by episodeyang** [remarkjs/remark-math#17]
In LaTeX, you can use `\begin{array}` without the `$$` b/c the array environment includes a standalone math environment. There are also text model LaTeX commands such as `\emph` that can be used in text (without `$` b/c they are textmode commands).

To achieve complete mixed LaTeX markdown syntax, we could add support to basic LaTeX command parsing + some white listed environments. We could even allow users to configure these white list and parsing rules.

----

`\[` is already in LaTeX macro land, so in this sense you are only one step away from adding support for something like this:

https://www.sharelatex.com/learn/Display_style_in_math_mode#Setting_mathematical_styles

```latex
In-line maths elements can be set with a different style: \(f(x) = \displaystyle \frac{1}{1+x}\). The same is true the other way around:
 
\begin{eqnarray*}
\begin{eqnarray*}
f(x) = \sum_{i=0}^{n} \frac{a_i}{1+x} \\
\textstyle f(x) = \textstyle \sum_{i=0}^{n} \frac{a_i}{1+x} \\
\scriptstyle f(x) = \scriptstyle \sum_{i=0}^{n} \frac{a_i}{1+x} \\
\scriptscriptstyle f(x) = \scriptscriptstyle \sum_{i=0}^{n} \frac{a_i}{1+x}
\end{eqnarray*}
\end{eqnarray*}
```

**Comment by Rokt33r** [comment]
I think it is too much for `remark-math`. 🤔  I suggest you to create another library to achieve it.

**Comment by wooorm** [comment]
I think the backslash will mess with markdown (as a backslash is an escape). I’d advice against this. So I’ll close it here.

If you‘d like it though, you can create your own plugins! Just like `remark-math`, and if it spits out `math` and `inlineMath` nodes, it’ll work with `rehype-katex`!
