### ISSUE TITLE
Use dashes for classes instead of camelCase

### ISSUE THREAD

**Issue by wooorm** [remarkjs/remark-math#31]
### Subject of the feature

Classes in HTML/CSS are typically written as lowercase and with dashes: `this-that`, not `thisThat`.

### Problem

This library uses camelcase.

### Expected behaviour

* Block math: `<div class="math math-display>`
* Inline math: `<span class="math math-inline>` (optionally with `math-display` class for `$$`)

/cc @Rokt33r

**Comment by wooorm** [comment]
If this is approved, I’d also want to suggest to drop the tag name check:

https://github.com/remarkjs/remark-math/blob/fd26772a91b9f5a56033451591c00f77cfd0691f/packages/rehype-katex/index.js#L28-L33

...And just check classes (that way HTML authors, so without `remark-math`, can use other tag names)

**Comment by Rokt33r** [comment]
Both make sense to me. I guess this should be major changes! I'll try it in this week.

**Comment by Rokt33r** [comment]
Oh you're already working on it! I'll keep tracking the changes then.

**Comment by wooorm** [comment]
Perfect! I’d like to see if KaTeX will move to hast, and based on that cut a new major release!
