### ISSUE TITLE
Rendered screenshot looks broken...

### ISSUE THREAD

**Issue by Rokt33r** [remarkjs/remark-math#36]
<img width="138" alt="Screen Shot 2019-09-03 at 1 51 20" src="https://user-images.githubusercontent.com/5865853/64127611-5b0c8080-cded-11e9-84cf-766083e1a034.png">

It renders `L` twice. I'll submit a pr in this weekends if no one working on it.

**Comment by ChristianMurphy** [comment]
@Rokt33r how did you resolve this?
A similar double render is being seen at https://spectrum.chat/unified/remark/remark-math-on-docusaurus-v2~220079aa-2dab-4d2e-b39a-a33563107dc5

**Comment by Rokt33r** [comment]
@ChristianMurphy Sorry I was too busy. And yeah, Titus's answer is right. It happens when the css is not loaded.
