### ISSUE TITLE
Will \( \) style math formula be supported

### ISSUE THREAD

**Issue by Ir1d** [remarkjs/remark-math#39]
### Subject of the feature

Describe your issue here.

in some mathjax configs people write `\(a+b\)` as formulas, will this be supported?

### Problem

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour

What should happen?  Please describe the desired behaviour.

parse `\(\)` as inline and `\[\]` as dispay

### Alternatives

What are the alternative solutions?  Please describe what else you have considered?

possible related #21

**Comment by wooorm** [comment]
While supporting this wouldn’t be too hard to implement (although brittle: the backslashes, parens, and square brackets will interfere with other Markdown constructs, whereas dollars are not in use), I’m not really in favor of adding it: I prefer that remark (and other markdown parsers) push a single way to do things. Having multiple ways to do a similar extension makes the Markdown you write less portable.

**Comment by Ir1d** [comment]
I totally agree with you. Lets stick with `$` and `$$`

**Comment by wooorm** [comment]
If someone wants this btw, `packages/remark-math` can be forked to add that. `rehype-katex` and such will still work if you expose the same math node in Markdown!

**Comment by Ir1d** [comment]
yeah I understand, that's nice. I believe using `$` only will be better, even though it takes more time to migrate, it's worth the effort.

**Comment by wooorm** [comment]
We’re not necessarily covering (la)tex here though: it’s about math in markdown in general, which could be mathml or asciimath syntax too.

And, see https://github.com/remarkjs/remark-math/issues/39#issuecomment-612572749: you can do this yourself if you want to!

**Comment by ChristianMurphy** [comment]
@travigd there's a fine line here.
Adding configuration for markers _may_ have value to discuss on it's own.

The push back is on reason presented which appears to be "it's in latex, so it should be here".
That is a non-goal, markdown is not latex.

If you want a latex transformer, contributions towards https://github.com/syntax-tree/ideas/issues/6 are welcome!
If there is a markdown focused reason, it may be worth exploring.

**Comment by travigd** [comment]
Sure, sure, I get it.

From my perspective, I'm just trying to give the best experience possible to the users of my editor (users who are at least partially accustomed to the `\(` syntax). I'm not arguing that this project should support all things LaTeX (e.g., supporting `\begin{align}`), but I **am** arguing that supporting `\(` is a very pragmatic thing to do.

**Comment by wooorm** [comment]
I don’t think it’d be good for markdown to standardize several syntaxes. I think we’re in a position to push for one syntax, as the most popular markdown parser, and I think we should do that. Again: you can do whatever you want with plugins, but I don‘t think we should make it easier.

**Comment by danny-avila** [comment]
> If someone wants this btw, packages/remark-math can be forked to add that. rehype-katex and such will still work if you expose the same math node in Markdown!

Can you give some examples on how to do this exactly? Looking at the package code, I'm a little lost albeit I haven't made my own plugin before.

**Comment by ChristianMurphy** [comment]
@danny-avila see the guide to plugins and ASTs at https://unifiedjs.com/learn/
And extending the parser at https://github.com/micromark/micromark#creating-a-micromark-extension

**Comment by xl0** [comment]
@wooorm It looks like OpenAI has decided to use the bracket syntax for its formulas:

https://chat.congusto.ai/public/9834ffd8-e15b-4d4f-83ad-057038e9239d (you can toggle md for the message)

Is there any chance you could reconsider the WONTFIX?

**Comment by ChristianMurphy** [comment]
> https://chat.congusto.ai/public/9834ffd8-e15b-4d4f-83ad-057038e9239d (you can toggle md for the message)

@xl0 did you share the right example?
The one you shared uses $ which is already supported.

> Is there any chance you could reconsider the WONTFIX?

Not at this time, and not for LLMs.
LLMs are masters of formatting things.
If your LLM of choice uses not standard markdown by default, prompt it to use standard markdown 🙂

**Comment by xl0** [comment]
@ChristianMurphy, yes:
```
<prompt>Demonstrate the use of math in markdown</prompt>
<d>easy</d>

You can use LaTeX syntax for math in Markdown, typically supported by platforms like GitHub, Jupyter, or Markdown processors with math support.

Inline math:  
`$E = mc^2$` renders as \( E = mc^2 \).

Block math:  
\```
$$
\int_0^1 x^2 \, dx = \frac{1}{3}
$$
\```
renders as:

\[
\int_0^1 x^2 \, dx = \frac{1}{3}
\]
```
So it uses the $$ syntax in the example, but then uses the \[ \( syntax actually to render the formulas.

I'm not saying, handle it by default, but an option would be great. I kind of see why they chose this style - it's less ambiguous. If it was just any LLM provider, I would not bother, but OpenAI kind of sets the tone for the ecosystem.

**Comment by wooorm** [comment]
It is recommending humans to use `$` though?

**Comment by ofk** [comment]
I have forked to support `\(` `\)`.

The core of the parser is [micromark/micromark-extension-math](/micromark/micromark-extension-math), and you can use the format by replacing it with [ofk/micromark-extension-llm-math](/ofk/micromark-extension-llm-math) (for example, through `resolve.alias` in vite).

I hope this helps with your implementation.

**Comment by remon-nashid** [comment]
@ofk you're a godsend! Where is that fork of yours?

**Comment by chricarp** [comment]
> [@ofk](https://github.com/ofk) you're a godsend! I'm so sick of the maintainers imaginary battle for a standard that no one called for. Now, how exactly can one use your fork with `remark-math`?

If you're using NextJS, it's simply a replace on webpack:
```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  pageExtensions: ['js', 'jsx', 'md', 'mdx', 'ts', 'tsx'],
  webpack: (config) => {
    config.resolve.alias['micromark-extension-math'] = 'micromark-extension-llm-math'
    return config
  }
}

export default nextConfig
```

**Comment by twxia** [comment]
> > [@ofk](https://github.com/ofk) you're a godsend! I'm so sick of the maintainers imaginary battle for a standard that no one called for. Now, how exactly can one use your fork with `remark-math`?
> 
> If you're using NextJS, it's simply a replace on webpack:
> 
> /** @type {import('next').NextConfig} */
> const nextConfig = {
>   pageExtensions: ['js', 'jsx', 'md', 'mdx', 'ts', 'tsx'],
>   webpack: (config) => {
>     config.resolve.alias['micromark-extension-math'] = 'micromark-extension-llm-math'
>     return config
>   }
> }
> 
> export default nextConfig

For NextJS's Turbopack: 

```
const nextConfig: NextConfig = {
  turbo: {
    resolveAlias: {
      "micromark-extension-math": "micromark-extension-llm-math",
    },
  },
};
```

**Comment by ChristopherChudzicki** [comment]
For what it's worth, I think MathJax's reasoning on why they disable the dollar sign syntax by default is very good:

>  For example, with single-dollar delimiters, “… the cost is $2.50 for the first one, and $2.00 for each additional one …” would cause the phrase “2.50 for the first one, and” to be treated as mathematics since it falls between dollar signs. 

I.e., dollar signs may not have a specific use within markdown (neither do backslashed parens, as far as I know), but they are very common in plaintext, particularly English plaintext.

The virtue of allowing configuration to **exclusively** support `\(...\)` and `\[...\]` is that **the same markdown renderer** can be used by two groups of people:
1. People who are completely ignorant of LaTeX but want to use dollar signs
2. People who are aware of LaTeX and want to write math.


It would be great to be able to configure support for either dollar-sign or `\(...\)`.
