### ISSUE TITLE
rehype-mathjax: mathjax is 500kb+ minzipped

### ISSUE THREAD

**Issue by wooorm** [remarkjs/remark-math#42]
### Subject of the feature

MathJax’ SVG output is heavy, probably due to its font support, figure out a way to make it smaller.

### Expected behaviour

Not be 500kb+ in browsers or in Node.

**Comment by nzt** [comment]
I can add an option to use CHTML in MathJax, but that option require to add path to webfont.
As you said, almost part of 500kb+ are font. I agree that it is good to have a option for users.

**Comment by wooorm** [comment]
So the external font option is only available for CHTML? 🤔

The docs seem to suggest that MathJax defaults to CHTML, and they prefer that. What is the reason for preferring SVG here?
