### ISSUE TITLE
I installed remark@13.0.0 but remark-math keeps warning me

### ISSUE THREAD

**Issue by rnarkk** [remarkjs/remark-math#52]
I'm using `remark-math` with `@mdx-js/loader`.

At build time, it keeps raising this warning and actually it never convert `$` and `$$`s.

`[remark-math] Warning: please upgrade to remark 13 to use this plugin`

**Comment by wooorm** [comment]
MDX is on remark@12, so the warning is correct, and this is an external problem.
You can use the previous version of remark-math for now, as mentioned in the [readme](https://github.com/remarkjs/remark-math/tree/main/packages/remark-math#important).

**Comment by rnarkk** [comment]
That helped a lot so thank you.
