### ISSUE TITLE
react-markdown example

### ISSUE THREAD

**Issue by majiang** [remarkjs/remark-math#55]
I'm rather new to TypeScript but would like to use this package with [react-markdown](https://github.com/remarkjs/react-markdown).  I've successfully loaded remarkGfm as following.  However, when I insert an equation, it is not properly processed.

```ts
import React, { useEffect, useState } from 'react'

import ReactMarkdown from 'react-markdown'
import rehypeKatex from 'rehype-katex'
import remarkGfm from 'remark-gfm'
import remarkMath from 'remark-math'

import './App.css'

function App()
{
    const [data, setData] = useState('Loading...')
    useEffect(() =>
    {
        async function fetchData()
        {
            const resp = await fetch('content/index.md')
            setData(await resp.text())
        }
        fetchData()
    })
    return <ReactMarkdown plugins={[remarkGfm, remarkMath, rehypeKatex]}>{data}</ReactMarkdown>
}

export default App;
```

## Expected Behavior
* LaTeX equations enclosed in `$`..`$`, `$$`..`$$`, `\(`..`\)`, or `\[`..`\]` are converted to KaTeX equations.

## Observed Behavior
* Equations with `$`..`$` or `$$`..`$$` resulted in `Error: Renderer for type `inlineMath` not defined or is not renderable` (I believe `$$`..`$$` is not inlineMath, but the error message was inlineMath)
* Equations with `\(`..`\)` or `\[`..`\]` was transformed to plaintext with `(`..`)` or `[`..`]` respectively

What am I missing?

**Comment by ChristianMurphy** [comment]
It is properly processed.
react-markdown currently does not support rehype plugins, like rehype katex https://github.com/remarkjs/react-markdown/issues/427
The error you are seeing says that there isn't a renderer for the `inlineMath` node type.

You can add a renderer by following the guide in the README for react-markdown https://github.com/remarkjs/react-markdown#use-a-plugin-and-custom-renderers-math
Or you could use React Remark, which supports rehype plugins https://github.com/remarkjs/react-remark, including rehype-katex https://remarkjs.github.io/react-remark/?path=/story/remark-component--markdown-with-math

**Comment by majiang** [comment]
Thank you @ChristianMurphy , I've followed your first suggestion and my equations are now rendered!

Now `$`..`$` is rendered as expected but `$$`..`$$` is also rendered as inline.  `\(`..`\)` and `\[`..`\]` is still plaintext.  I'll look into this for myself.

**Comment by ChristianMurphy** [comment]
https://github.com/remarkjs/remark-math/issues/39
