### ISSUE TITLE
Update Katex from 0.12.0 to its latest available version 0.13.2 [rehype-katex]

### ISSUE THREAD

**Issue by karuifeather** [remarkjs/remark-math#58]
### Update Katex from 0.12.0 to its latest available version 0.13.2

The current version gives a nasty `Katex Parse Error: No environment found...` when processing Latex that involves `\begin{equation}` and other similar features.

### Your environment

Is irrelevant.

### Steps to reproduce

This markdown causes it to trip.

```markdown
$$
\begin{equation}
    \gamma^2+\theta^2=\omega^2
\end{equation}
$$
```

### Expected behavior

Math should be correctly converted to HTML?

### Actual behavior

Throws a Katex Error, which does not happen with the updated Katex package.

### Solution

I manually updated Katex to its latex version and got it to work.

**Comment by wooorm** [comment]
thanks, fixed!
