### ISSUE TITLE
katex error: Module parse failed: Identifier directly after number

### ISSUE THREAD

**Issue by jackykwandesign** [remarkjs/remark-math#65]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

"rehype-katex": "^6.0.1"

### Link to runnable example

https://github.com/jackykwandesign/react-markdown-katex-error

### Steps to reproduce

1. just use rehype-katex in react-markdown will produce error

### Expected behavior

show katex

### Actual behavior

show babel-loader error

```
Failed to compile.

./node_modules/hast-util-to-text/index.js 363:65
Module parse failed: Identifier directly after number (363:65)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|     //     break is the zero-width space character (U+200B), then the break is
|     //     removed, leaving behind the zero-width space.
>     if (lines[index].charCodeAt(lines[index].length - 1) === 0x20_0b
|     /* ZWSP */
|     || index < lines.length - 1 && lines[index + 1].charCodeAt(0) === 0x20_0b
```

### Runtime

Node v12

### Package manager

yarn v1

### OS

Linux

### Build and bundle tools

Create React App

**Comment by ChristianMurphy** [comment]
The error is coming from `hast-util-to-text`.
This is being discussed at https://github.com/syntax-tree/hast-util-to-text/issues/4#issuecomment-907794296

**Comment by ustcsy** [comment]
same problem, React 17.0.2

**Comment by wooorm** [comment]
Then please comment on the place where the discussion is being held about this problem with details.

**Comment by MagicMarvel** [comment]
I am a freshman in programing and can't understand your solution, but i found using the specific version remark-math@4.0.0 would deal with this problem.

**Comment by wooorm** [comment]
Please see the linked discussion, read through it, and provide information there

**Comment by wooorm** [comment]
solved over there
