### ISSUE TITLE
The dollar sign is not showing in single $ quote

### ISSUE THREAD

**Issue by jackykwandesign** [remarkjs/remark-math#74]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

    "rehype-katex": "^6.0.2",     "remark-math": "^5.1.1",

### Steps to reproduce

Markdown viewer, children is just the markdown text

```ts
import ReactMarkdown from "react-markdown";
import remarkMath from "remark-math";
import rehypeKatex from "rehype-katex";
import "katex/dist/katex.min.css"; // `rehype-katex` does not import the CSS for you

<ReactMarkdown
	remarkPlugins={[remarkMath]}
	rehypePlugins={[rehypeKatex]}
>
	{props.children}
</ReactMarkdown>
```

### Expected behavior

give 
```
$$
\$10
$$
```

or 

```
$
\$10
$
```

will show 
```
$10
```

### Actual behavior

Only double $$ sign quote can show correct dollar currency symbol, single quote can't show

![image](https://user-images.githubusercontent.com/46065771/156166792-9f665aa9-b371-4efd-b647-4fb8890ad413.png)

### Runtime

Node v16

### Package manager

yarn 2

### OS

Linux

### Build and bundle tools

Create React App

**Comment by wooorm** [comment]
This is intentional behavior. The same occurs for code.

````
```
`10
```
````

```
`10
```

````
`
`10
`
````

`
`10
`

**Comment by m4ttsch** [comment]
Hey! I am also seeing this behavior. Is there a way to render escape dollar signs in inline-mode or am I SOL?

**Comment by wooorm** [comment]
Yes there is. Just like with code, use more dollars.

    Aaa $$ math $ also math $$ bbb

**Comment by jackykwandesign** [comment]
actually i found lib https://www.npmjs.com/package/markdown-it-katex is supporting inline dollar sign with `$ \$123 $` format, and tools such as`Notions` is following this convention

![image](https://github.com/remarkjs/remark-math/assets/46065771/008b114e-fffd-4e8a-81ca-168621d06d99)

so maybe current behavior is not convenience and not compatible

**Comment by wooorm** [comment]
There is no spec, no two tools are going to be the same.
The smartest thing to do then, is to stick to markdown, in this case, how code works. And that’s what we do.

**Comment by jackykwandesign** [comment]
> 

seems it is underlayer difference between `pandoc` and `commonmark`
