### ISSUE TITLE
Hard break identifier immediately preceding $$ is not registered as a hard break.

### ISSUE THREAD

**Issue by abhinandshibu** [remarkjs/remark-math#78]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

"remark-math": "^5.1.1", "rehype-katex": "^6.0.2",

### Steps to reproduce

```
import ReactMarkdown from "react-markdown";
import remarkMath from "remark-math";
import remarkBreaks from "remark-breaks"
import rehypeKatex from "rehype-katex";
import "katex/dist/katex.min.css";

<ReactMarkdown
      remarkPlugins={[remarkMath, remarkBreaks]}
      rehypePlugins={[rehypeKatex]}
    >
   {markdownText}
</ReactMarkdown>
```

### Expected behavior

A hard break can be caused by `␠␠` or by `\`.

When `markdownText = "empty \n \ \n line"`
It produces:
```
new
line
empty

line
```
as expected.

Though if we are using `$$` then the hard break characters are not converted into a hard break.
When `markdownText = "new line empty \n \ \n $$line$$"`
We expect:
```
new
line
empty

line
```
With the last `line` being written in latex.

### Actual behavior

It actually produces:
```
new
line
empty
line
```
With the last `line` being written in latex.

This is the same no matter how many new lines and hard breaks are placed before it.
eg. `markdownText = "new \n line \n empty \n \ \n \ \n \ \n \ \n \ \n $$line$$"`

### Runtime

Node v17

### Package manager

npm 8

### OS

macOS

**Comment by wooorm** [comment]
I don’t quite understand what you are asking: you have superfluous slashes in your code and you keep using one superfluous space, but one space does nothing.

If you are asking about:

````markdown
new
line
empty\

```code
line
```
````

And that that `\` does not produce a hard break.
Then that’s correct. Hard breaks work *inside* paragraphs. Not at the end of them.

If you are asking about something else, can you please clarify your examples, and make a reproduction?

**Comment by abhinandshibu** [comment]
I see, apologies that is my misunderstanding.
