### ISSUE TITLE
Next.js hydration issue

### ISSUE THREAD

**Issue by nguyenvukhang** [remarkjs/remark-math#80]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

remark-math, rehype-mathjax, all latest versions

### Steps to reproduce

`yarn create next-app`
`yarn add @next/mdx @mdx-js/loader @mdx-js/react remark-math rehype-mathjax`

create a `next.config.mjs` with the contents:

```js
import mdx from "@next/mdx";
import remarkMath from "remark-math";
import rehypeMathJax from "rehype-mathjax";

const withMDX = mdx({
  extension: /\.mdx?$/,
  options: {
    remarkPlugins: [remarkMath],
    rehypePlugins: [rehypeMathJax],
  },
});

export default withMDX({
  reactStrictMode: true,
  pageExtensions: ["tsx", "jsx", "mdx"],
});

```

### Expected behavior

Should render without errors.

### Actual behavior

Renders correctly, but with the error
`Error: Text content does not match server-rendered HTML.`

### Runtime

Node v16

### Package manager

yarn 1

### OS

macOS

### Build and bundle tools

Next.js (bug is seen on both v13 and v12)

**Comment by nguyenvukhang** [comment]
This error disappear when commenting out lines 113-115 in https://github.com/remarkjs/remark-math/blob/7e82f934e77d62b7366825633bc7f1d5d5e5a861/packages/rehype-mathjax/lib/create-plugin.js

```js
      if (found && renderer.styleSheet) {
        context.children.push(renderer.styleSheet())
      }
```

**Comment by wooorm** [comment]
well, the root cause is that there is different handling on the server (JSDOM) and a browser (depending on which one your users use). Not sure it can be change,d but feel free to investigate it.

**Comment by hkhanna** [comment]
I'm having this problem too. One thing I've noticed is that if you inspect a mathjax-generated element, you'll see something like this: `<mjx-container classname="MathJax ...>`

It should say `class=`, not `classname=` when you're inspecting in the browser. For some reason, when combined with MDX, it doesn't properly convert that attribute. If I don't use MDX and use Next.js directly, it works fine, so it has something to do with remark-math and MDX together, I think.

**Comment by wooorm** [comment]
That seems like a very different problem? The above seems to talk about CSS, you seem to talk about MathML?

**Comment by hkhanna** [comment]
I'm not talking about MathML, at least I don't think I am. 

I'm talking about how rehype-mathjax renders the HTML. Just suggesting a possible cause of the hydration error. If somehow it was being rendered as "class" on the server but "classname" on the client, I think that could cause the hydration error. 

Interestingly, when I commented out the lines OP suggested, I still got the error. If I switch to rehype-katex the problem goes away.

**Comment by wooorm** [comment]
oh sorry yeah you’re right, `mjx-container` is a custom element, not mathml.

> when I commented out the lines OP suggested, I still got the error

Yeah, I thought it was a different problem, and this seems to indicate that.

> If I switch to rehype-katex the problem goes away.

It does thing completely differently!

**Comment by fullykubed** [comment]
Can confirm this issue still exists with Next.js 14

**Comment by fullykubed** [comment]
Can confirm that this [solution](https://github.com/remarkjs/remark-math/issues/80#issuecomment-1362268548) that avoids adding the css appears to work.

**Comment by sweetim** [comment]
is been a while, any update or workaround for this?

**Comment by wooorm** [comment]
This is a problem with Next or React, as it can be reproduced without all these packages.
Replacing `page.tsx`, or a similar Next app page, with:

```tsx
export default function Home() {
  return (
    <div>
      <main>
        <style>[title="a"] &#x7b; color: violet &#x7d;</style>
        <div title="a">Hi!</div>
      </main>
    </div>
  );
}
```

While this works (the `div` becomes violet), it yields the react warning:

```
Warning: Text content did not match. Server: "a[b=&quot;c&quot;] { color: red }" Client: "a[b="c"] { color: red }"
    at style
    at main
    at div
    at Home (Server)
```

And then the Next error:

```
Uncaught Error: Text content does not match server-rendered HTML.
See more info here: https://nextjs.org/docs/messages/react-hydration-error
```

Please raise this with Next/React. Thanks

**Comment by alexharri** [comment]
For anyone else encountering this, I'm working around the issue like so:

```ts
import { SerializeOptions } from "next-mdx-remote/dist/types";

async function rehypeMathjax() {
  const plugin = (await import("rehype-mathjax/svg")).default({ svg: { scale: 1 } });
  return () => (tree: import("hast").Root) => {
    plugin(tree);

    // If the last added child in the tree is a stylesheet containing 'mjx-container',
    // remove it. It causes Next.js hydration errors.
    //
    // Workaround for https://github.com/remarkjs/remark-math/issues/80.
    const lastChild = tree.children[tree.children.length - 1];
    if (lastChild.type === "element" && lastChild.tagName === "style") {
      const content = lastChild.children[0];

      // Make sure that this is a Mathjax related stylesheet before removing it.
      const isMathjaxStylesheet =
        content.type === "text" && content.value.includes("mjx-container");
      if (isMathjaxStylesheet) {
        tree.children.pop(); // Remove!
      }
    }
  };
}

export const getMdxOptions = async (): Promise<SerializeOptions["mdxOptions"]> => ({
  remarkPlugins: [(await import("remark-math")).default],
  rehypePlugins: [await rehypeMathjax()],
});
```

On the library side, it would be nice if it was possible to disable the stylesheet injection via an option like `injectStylesheet: false`.

**Comment by wooorm** [comment]
Please see my comment before yours. It would be nice if you raise this in the correct place? Which I believe to be next, so that it can be solved. Thank you
