### ISSUE TITLE
Math and Katex renders incorrectly

### ISSUE THREAD

**Issue by jkim34** [remarkjs/remark-math#83]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

"rehype-katex": "^6.0.3", "remark-math": "^5.1.1"

### Steps to reproduce

Use [codesandbox](https://codesandbox.io/embed/nervous-ramanujan-cd0uvr) to reproduce.

If link doesn't work, simply add below packages:
"rehype-katex": "^6.0.3", "remark-math": "^5.1.1"

Use npm v 9.2.0, or simply use codesandbox's default runtime.

### Expected behavior

`$x^2 + y^2 = z^2$` should render correctly.

### Actual behavior

After correctly rendering, it also appends `x2+y2=z2`

### Runtime

Node v14

### Package manager

Other (please specify in steps to reproduce)

### OS

Windows

### Build and bundle tools

Create React App

**Comment by ChristianMurphy** [comment]
Hey @jkim34! 👋 
Please follow the usage guide in the readme. https://github.com/remarkjs/remark-math/tree/main/packages/rehype-katex#use
Notably, katex requires a stylesheet to render correctly, you haven't included the CSS stylesheet, so it won't be styled correctly.
Add the stylesheet.
