### ISSUE TITLE
Update KaTeX types

### ISSUE THREAD

**Issue by radarfox** [remarkjs/remark-math#86]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Please, update `@types/katex` dependency to v0.16 to match the dependency `katex@^0.16.0` that is used in `rehype-katex`. Otherwise, two `@types/katex` dependencies will be installed in my project. The other coming from `micromark-extension-math@2.1.2` (the latest version `3.0.0` also uses types v0.16).

### Solution

`npm update @types/katex@^0.16.0`

### Alternatives

None

**Comment by remcohaszing** [comment]
Yes, definitely. Would you like to create a PR?

**Comment by wooorm** [comment]
Hi!

Everything will be updated.
Updating everything takes months.
It’s not beneficial to have some issues about some updates open, so I’ll close this.
I’ll get to it!

**Comment by remcohaszing** [comment]
This issue is more about aligning the `katex` and `@types/katex` dependencies than making sure they are up-to-date. However, knowing that everything in the unified is in the progress of being updated, I agree.
