### ISSUE TITLE
Mathjax Docs are Incorrect Due to Removal of index.js

### ISSUE THREAD

**Issue by nkeil** [remarkjs/remark-math#87]
### Affected packages and versions

Rehype-Mathjax v5.0.0

### Steps to reproduce

In the commit https://github.com/remarkjs/remark-math/commit/4223ed9d10257db66fd526716504ce9832f15ff1, `rehype-mathjax/index.js` was removed. This has resulted in our existing code failing when upgrading to `5.0.0`.

```js
import rehypeMathJax from 'rehype-mathjax';
```

This method of importing is currently recommended on the documentation. Either a default export should be added back, or the docs should be updated to use one of the other ways of importing (`/browser`, `/svg`, etc.)

**Comment by nkeil** [comment]
After some more research, I discovered that this issue was due to an ESM incompatibility with the `exports` field in package.json ([link](https://stackoverflow.com/a/70020984)). Because `"type": "module"` would be a big headache, I just changed the tsconfig to `"moduleResolution": "bundler"` (this is using [Next.js](https://github.com/tsconfig/bases/blob/main/bases/next.json)), and the default export worked.

**Comment by remcohaszing** [comment]
> I just changed the tsconfig to `"moduleResolution": "bundler"`

I'm just confirming this is the correct setting for bundlers such as Next.js. You also need `"module": "esnext"`, but you probably already have that.
