### ISSUE TITLE
Cannot read properties of undefined (reading 'mathFlowInside')

### ISSUE THREAD

**Issue by twobit** [remarkjs/remark-math#89]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

remark-math@6

### Steps to reproduce

Using block LaTeX formatting causes an error:

```
$$
\theta
$$
```

### Expected behavior

Block LaTeX formatting should be supported.

### Actual behavior

```
Cannot read properties of undefined (reading 'mathFlowInside')
```

### Runtime

Node v17

### Package manager

npm 8

### OS

macOS

### Build and bundle tools

Next.js

**Comment by twobit** [comment]
Looks like Nextra [ran into this issue](https://github.com/shuding/nextra/blob/8ff0576d60d2fabb4bb9f0d64ee4261928195ba7/packages/nextra/CHANGELOG.md?plain=1#L7C1-L7C1) too:

```
ad7b31b0: downgrade remark-math from `6` to `5.1.1` to fix
  `TypeError: Cannot read properties of undefined (reading 'mathFlowInside')`
  error
```

**Comment by ChristianMurphy** [comment]
@twobit your `remark` and `remark-math` versions need to be matched.
Either upgrade both at the same time, or hold both on the previous major

**Comment by wooorm** [comment]
That should work. You probably use something else too?

**Comment by lloydjatkinson** [comment]
I have the following (it's an Astro site):

```json
    "rehype-katex": "^7.0.0",
    "rehype-mathjax": "^5.0.0",
    "rehype-slug": "^6.0.0",
    "remark": "^15.0.1",
    "remark-math": "^6.0.0",
    "remark-mdx": "^2.3.0",
    ...
    "@astrojs/mdx": "^1.1.2",
 ```
 
 With the following MDX file:
 
 ```mdx
 ---
dates:
    published: 2023-08-31T09:53:07+0000
---
Trying out maths rendering via markdown.

This is an inline *equation:* $$V_{sphere} = \frac{4}{3}\pi r^3$$, followed by a display style equation after lots more lines of paragraph to test vertical alignment of inline expressions as well as the standalone expressions.
Here is also some **styled text**.

This is another inline expression $$\sum_{i=0}^n i^2 = \frac{(n^2+n)(2n+1)}{6}$$ followed by a normal expression, which align to the ___middle___ of the content:

$$
```

And the following setup:

```ts
export default defineConfig({
    markdown: {
        remarkPlugins: [remarkMath],
    },
    integrations: [
        astroExpressiveCode({
            theme: 'light-plus',
            styleOverrides: {
                borderRadius: () => '0',
            },
            frames: {
                styleOverrides: {
                    frameBoxShadowCssValue: 'none',
                },
            },
        }),
        preact({
            include: ['**/preact/*'],
        }),
        react({
            include: ['**/react/*'],
        }),
        mdx({
            rehypePlugins: [
                [rehypeSlug],
                [rehypeMathJax],
            ],
        }),
    ],
});
```

**Comment by wooorm** [comment]
Thanks for providing more info.
The `remark` package you have is not used.
The remark plugins are used inside MDX.
MDX is not yet updated.
Uninstall `remark`, downgrade `remark-gfm`.
When MDX is updated, update everything.

**Comment by lloydjatkinson** [comment]
Unfortunately I believe remark-gfm is brought in by Astro

**Comment by wooorm** [comment]
I’d assume they have a working version?

**Comment by FriendlyLifeguard** [comment]
I also had this issue until I used this tutorial : https://ileumas.com/writing/2022/03/astro-math-katex/
as well as enclosing the equation by $$ on the same line . 

This is my astro.config.js : 

```
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';

// https://astro.build/config
export default defineConfig({
	// ! Please remember to replace the following site property with your own domain
	site: "https://alankang.xyz",
	markdown: {
		remarkPlugins: [remarkUnwrapImages, remarkReadingTime, remarkMath],
		remarkRehype: { footnoteLabelProperties: { className: [""] } },
		shikiConfig: {
			theme: "dracula",
			wrap: true,
		},
		rehypePlugins: [
			[rehypeKatex, {}]
		]
	},
```

**Comment by wooorm** [comment]
The `footnoteLabelProperties` looks weird? You likely shouldn’t set that at all.

As for `remark-gfm` I mentioned earlier, that should’ve been `remark-math`

**Comment by yklcs** [comment]
Astro is [currently on](https://github.com/withastro/astro/blob/4983acea8c7a1b2747ceea6a5d0b31003567d05a/packages/markdown/remark/package.json) `remark-parse`/`unified` 10, which is incompatible with `remark-math` 6, giving the error `Cannot read properties of undefined (reading 'mathFlowInside')`. Downgrading to `remark-math` 5 solved this issue for me.

**Comment by ChristianMurphy** [comment]
@iwasrobbed reading the thread would help.
To reiterate, make sure all of your remark and mdx packages are at the latest version.
If you are using remark or mdx though another framework like next or astro. Make sure you are using the latest version of their framework and that they have the latest version of remark and mdx.

Locking this thread as resolved "same" follow up comments don't add anything.
If folks have a specific question, the Q&A forum is open.
https://github.com/orgs/remarkjs/discussions
Please specify how you are using remark and remark math, and the specific versions being used.
