### ISSUE TITLE
[Nuxt MDC] reading 'mathFlowInside' undefined when parsing a multi-line formula

### ISSUE THREAD

**Issue by Sun-ZhenXing** [remarkjs/remark-math#91]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

remark-math@6.0.0

### Link to runnable example

https://stackblitz.com/edit/nuxt-starter-9lhesd?file=README.md

### Steps to reproduce

I'm trying to use [`@nuxtjs/mdc`](https://github.com/nuxt-modules/mdc), which is a similar technology to MDX.

I think this is a bug in `remark-math`, not Nuxt MDC.

---

Repo: <https://stackblitz.com/edit/nuxt-starter-9lhesd?file=README.md>.

Steps: Input `$123$` or `$$123$$` work well, but got error when entering a multi-line formula.

e.g:

```markdown
$$
123
$$
```

### Expected behavior

No error.

### Actual behavior

Error:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'mathFlowInside')
    at Object.exitMathFlowFence (remark-math.js?v=49db5ce9:140:19)
    at compile (index.js?v=49db5ce9:363:40)
    at fromMarkdown (index.js?v=49db5ce9:193:31)
    at parser (index.js?v=49db5ce9:18:12)
    at Function.parse (index.js?v=49db5ce9:668:12)
    at executor (index.js?v=49db5ce9:734:40)
    at new Promise (<anonymous>)
    at Function.process (index.js?v=49db5ce9:720:47)
    at parseMarkdown (index.mjs?v=49db5ce9:35:41)
    at async main (app.vue:6:15)
```

### Runtime

Other (please specify in steps to reproduce)

### Package manager

Other (please specify in steps to reproduce)

### OS

Other (please specify in steps to reproduce)

### Build and bundle tools

Vite

**Comment by wooorm** [comment]
Report this with nuxt: they should update there tools.
Or downgrade our packages for now

**Comment by Sun-ZhenXing** [comment]
Thanks, I will report this issue to Nuxt.

**Comment by wokalek** [comment]
I have the same issue!
