### ISSUE TITLE
Older version of `jsdom` (<23) causes deprecation warnings

### ISSUE THREAD

**Issue by stephenlrandall** [remarkjs/remark-math#93]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

rehype-mathjax

### Steps to reproduce

Install `rehype-mathjax` with npm/pnpm/yarn

### Expected behavior

No deprecated warnings

### Actual behavior

The following deprecation warnings (pnpm):

```
 WARN  2 deprecated subdependencies found: abab@2.0.6, domexception@4.0.0
```

Both of these are used by older versions of `jsdom` (<23), but have been removed in `jsdom` v23 after being deprecated.

### Package manager

pnpm

### OS

macOS

### Build and bundle tools

Vite

**Comment by ChristianMurphy** [comment]
Welcome @stephenlrandall! 👋 
Warning's are not necessarily a bug, it still works and is secure 🙂 
That said a PR upgrading JSDom to latest would also be welcome.

**Comment by stephenlrandall** [comment]
Yeah, I wasn’t sure exactly what to classify this as. I’d be happy to provide a PR — I assume that all packages use this dependency, and there’s some test suite that should pass?

**Comment by ChristianMurphy** [comment]
> I assume that all packages use this dependency

only the `rehype-mathjax` package https://github.com/search?q=repo%3Aremarkjs%2Fremark-math%20jsdom&type=code

> there’s some test suite that should pass?

Yes, running `npm test` runs a test suite, static analysis tools, and a type checker.

**Comment by stephenlrandall** [comment]
@ChristianMurphy Opened https://github.com/remarkjs/remark-math/pull/94. All tests passed.
