### ISSUE TITLE
Add a rehype plugin to use mathlive renderer

### ISSUE THREAD

**Issue by 66Leo66** [remarkjs/remark-math#95]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

I'd like to use https://github.com/arnog/mathlive to generate markups for math formula.

### Solution

Add a new package `rehype-mathlive`. Mathlive has [decent SSR support](https://cortexjs.io/mathlive/guides/static/) and requires no browser-side dependency but only a css. It has nice support for latex commands and also mhchem out-of-the-box. Also I think it's based on custom fonts so it looks nice and can be easily sclaed up and down for example.

### Alternatives

Given that `rehype-katex` is implemented in a single file, I think intergating mathlive won't be too difficult. If acceptable, I could try to do it on my own and send a PR, though I'm not so familiar with remark/rehype.

**Comment by JounQin** [comment]
You can write your own package `rehype-mathlive` first to judge whether it works as expected.
