### ISSUE TITLE
rehype-katex breaks in production build

### ISSUE THREAD

**Issue by losh11** [remarkjs/remark-math#96]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.0.0 and 6.0.2 

### Steps to reproduce

Using bun with a Nextjs 13.5.4 project. Node v18.

### Expected behavior

It should work.

### Actual behavior

Errors with message:

```bash
./contentlayer.config.ts:114:7
Type error: Type '(options?: Readonly<Options> | null | undefined) => (tree: Root, file: VFile) => undefined' is not assignable to type 'Pluggable<any[]>'.
  Type '(options?: Readonly<Options> | null | undefined) => (tree: Root, file: VFile) => undefined' is not assignable to type 'Plugin<any[], any, any>'.
    Type '(tree: Root, file: VFile) => undefined' is not assignable to type 'void | Transformer<any, any>'.
      Type '(tree: Root, file: VFile) => undefined' is not assignable to type 'Transformer<any, any>'.
        Types of parameters 'file' and 'file' are incompatible.
          Type 'import("/Users/loshan/Repos/ltc/foss-ltc/node_modules/vfile/lib/index").VFile' is not assignable to type 'import("/Users/loshan/Repos/ltc/foss-ltc/node_modules/rehype-katex/node_modules/vfile/lib/index").VFile'.
            Types of property 'messages' are incompatible.
              Type 'import("/Users/loshan/Repos/ltc/foss-ltc/node_modules/vfile-message/index").VFileMessage[]' is not assignable to type 'import("/Users/loshan/Repos/ltc/foss-ltc/node_modules/rehype-katex/node_modules/vfile/node_modules/vfile-message/lib/index").VFileMessage[]'.
                Type 'VFileMessage' is missing the following properties from type 'VFileMessage': ancestors, place

  112 |       rehypeSlug,
  113 |       rehypeAutolinkHeadings,
> 114 |       rehypeKatex,
      |       ^
  115 |       [rehypeCitation, { path: path.join(root, 'data') }],
  116 |       [rehypePrismPlus, { ignoreMissing: true }],
  117 |       rehypePresetMinify,
error: script "build" exited with code 1
```

### Runtime

Other (please specify in steps to reproduce)

### Package manager

npm 8, Other (please specify in steps to reproduce)

### OS

Linux, macOS

### Build and bundle tools

Next.js

**Comment by ChristianMurphy** [comment]
Welcome @losh11! 👋 
Sorry you ran into a spot of trouble.

The issue you share appears to be a typescript error.
Make sure you are running the latest major version of all: remark, rehype, unified, and vfile dependencies.
The error indicates you likely have incompatible major versions installed currently.

**Comment by JounQin** [comment]
You need provide reproduction so that we can help to check in detail.

**Comment by wooorm** [comment]
Most likely: update all your tools. Raise issues with the ones that are not up to date (this package is up to date).
